### ISSUE TITLE
报错啊

### ISSUE THREAD

**Issue by kklldog** [OpenSISE/web_login_cracker#1]
File "D:\Tools\web_login_cracker-master\web_login_cracker.py", line 39
    except IOError, e:
                  ^
SyntaxError: invalid syntax

python版本问题吗？

**Comment by lcatro** [comment]
@kklldog 仔细看,这是一个语法错误..

**Comment by kklldog** [comment]
@lcatro 大哥，这个cracker不是我写的啊，另外python我不会啊。。。

**Comment by lcatro** [comment]
@kklldog 应该是python 版本问题,看代码好像写的时候用的是python 2 ..

**Comment by hadg** [comment]
@kklldog 用python2

**Comment by xingrz** [comment]
知乎搜索：`如何正确地提问`
